name: Run Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pandas pyarrow pydantic
      - name: Run tests
        run: |
          export PYTHONPATH=${PYTHONPATH}:$(pwd)/scripts
          export TEST_MODE=true
          pytest tests/ -v
        shell: /usr/bin/bash -e {0}
        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.11.13/x64
          PKG_CONFIG_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib/pkgconfig
          Python_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
          Python2_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
          Python3_ROOT_DIR: /opt/hostedtoolcache/Python/3.11.13/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.13/x64/lib